channels:
- conda-forge
dependencies:
- python=3.12.11
- pip<=25.2
- pip:
  - mlflow==3.10.0
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.0.0
  - pyarrow==23.0.1
  - scikit-learn==1.8.0
  - scipy==1.17.1
name: mlflow-env
